
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    flow.knative.dev/release: devel
    knative.dev/crd-install: "true"
    duck.knative.dev/addressable: "true"
  name: statemachines.flow.knative.dev
spec:
  group: flow.knative.dev
  names:
    kind: StateMachine
    listKind: StateMachineList
    plural: statemachines
    singular: statemachine
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: StateMachine is the Schema for the workflows API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: StateMachineSpec defines the desired state of Workflow
              properties:
                stateMachine:
                  description: '@TODO: delete from here This comes from StateMachineRunner'
                  properties:
                    stateMachineStates:
                      properties:
                        states:
                          additionalProperties:
                            description: State binds a state with an action and a set
                              of events it can handle.
                            properties:
                              events:
                                additionalProperties:
                                  description: StateType represents an extensible state
                                    type in the state machine.
                                  type: string
                                description: Events represents a mapping of events and
                                  states.
                                type: object
                            type: object
                          description: States represents a mapping of states and their
                            implementations.
                          type: object
                      required:
                        - states
                      type: object
                    version:
                      type: string
                  required:
                    - stateMachineStates
                  type: object
              type: object
            status:
              description: StateMachineStatus defines the observed state of Workflow
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []