
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - flow.knative.dev
  resources:
  - statemachinerunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flow.knative.dev
  resources:
  - statemachinerunners/finalizers
  verbs:
  - update
- apiGroups:
  - flow.knative.dev
  resources:
  - statemachinerunners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - flow.knative.dev
  resources:
  - statemachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flow.knative.dev
  resources:
  - statemachines/finalizers
  verbs:
  - update
- apiGroups:
  - flow.knative.dev
  resources:
  - statemachines/status
  verbs:
  - get
  - patch
  - update
