
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eventing.knative.dev
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowrunners/finalizers
  verbs:
  - update
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowrunners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowruns/finalizers
  verbs:
  - update
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflows/status
  verbs:
  - get
  - patch
  - update
