# permissions for end users to view workflowruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflowrun-viewer-role
rules:
- apiGroups:
  - workflow.com.salaboy
  resources:
  - workflowruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workflow.com.salaboy
  resources:
  - workflowruns/status
  verbs:
  - get
