# permissions for end users to edit workflowruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflowrun-editor-role
rules:
- apiGroups:
  - workflow.com.salaboy
  resources:
  - workflowruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflow.com.salaboy
  resources:
  - workflowruns/status
  verbs:
  - get
