# permissions for end users to view workflowrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflowrunner-viewer-role
rules:
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowrunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowrunners/status
  verbs:
  - get
