# permissions for end users to view workflowruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflowrun-viewer-role
rules:
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workflow.knative.dev
  resources:
  - workflowruns/status
  verbs:
  - get
