apiVersion: flow.knative.dev/v1
kind: StateMachine
metadata:
  name: buy-tickets-statemachine
spec:
  stateMachine:
    version: "1.0.0"
    stateMachineStates:
      states:
        "":
          events:
            JoinedQueue: InQueue
        InQueue:
          events:
            ExitedQueue: BuyingTickets
            AbandonedQueue: NoTicketsPurchased
        BuyingTickets:
          events:
            TicketsReserved: PayingTickets
        PayingTickets:
          events:
            PaymentRequested: WaitingForPaymentAuth
        WaitingForPaymentAuth:
          events:
            PaymentAuthorized: TicketsPurchased
        TicketsPurchased:
          events: { }
        NoTicketsPurchased:
          events: { }
