/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	statev1 "github.com/salaboy/knative-state/pkg/apis/state/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStateMachines implements StateMachineInterface
type FakeStateMachines struct {
	Fake *FakeFlowV1
	ns   string
}

var statemachinesResource = schema.GroupVersionResource{Group: "flow.knative.dev", Version: "v1", Resource: "statemachines"}

var statemachinesKind = schema.GroupVersionKind{Group: "flow.knative.dev", Version: "v1", Kind: "StateMachine"}

// Get takes name of the stateMachine, and returns the corresponding stateMachine object, and an error if there is any.
func (c *FakeStateMachines) Get(ctx context.Context, name string, options v1.GetOptions) (result *statev1.StateMachine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(statemachinesResource, c.ns, name), &statev1.StateMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*statev1.StateMachine), err
}

// List takes label and field selectors, and returns the list of StateMachines that match those selectors.
func (c *FakeStateMachines) List(ctx context.Context, opts v1.ListOptions) (result *statev1.StateMachineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(statemachinesResource, statemachinesKind, c.ns, opts), &statev1.StateMachineList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &statev1.StateMachineList{ListMeta: obj.(*statev1.StateMachineList).ListMeta}
	for _, item := range obj.(*statev1.StateMachineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stateMachines.
func (c *FakeStateMachines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(statemachinesResource, c.ns, opts))

}

// Create takes the representation of a stateMachine and creates it.  Returns the server's representation of the stateMachine, and an error, if there is any.
func (c *FakeStateMachines) Create(ctx context.Context, stateMachine *statev1.StateMachine, opts v1.CreateOptions) (result *statev1.StateMachine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(statemachinesResource, c.ns, stateMachine), &statev1.StateMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*statev1.StateMachine), err
}

// Update takes the representation of a stateMachine and updates it. Returns the server's representation of the stateMachine, and an error, if there is any.
func (c *FakeStateMachines) Update(ctx context.Context, stateMachine *statev1.StateMachine, opts v1.UpdateOptions) (result *statev1.StateMachine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(statemachinesResource, c.ns, stateMachine), &statev1.StateMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*statev1.StateMachine), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStateMachines) UpdateStatus(ctx context.Context, stateMachine *statev1.StateMachine, opts v1.UpdateOptions) (*statev1.StateMachine, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(statemachinesResource, "status", c.ns, stateMachine), &statev1.StateMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*statev1.StateMachine), err
}

// Delete takes name of the stateMachine and deletes it. Returns an error if one occurs.
func (c *FakeStateMachines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(statemachinesResource, c.ns, name), &statev1.StateMachine{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStateMachines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(statemachinesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &statev1.StateMachineList{})
	return err
}

// Patch applies the patch and returns the patched stateMachine.
func (c *FakeStateMachines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *statev1.StateMachine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(statemachinesResource, c.ns, name, pt, data, subresources...), &statev1.StateMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*statev1.StateMachine), err
}
