/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/salaboy/knative-state/pkg/apis/state/v1"
	scheme "github.com/salaboy/knative-state/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StateMachinesGetter has a method to return a StateMachineInterface.
// A group's client should implement this interface.
type StateMachinesGetter interface {
	StateMachines(namespace string) StateMachineInterface
}

// StateMachineInterface has methods to work with StateMachine resources.
type StateMachineInterface interface {
	Create(ctx context.Context, stateMachine *v1.StateMachine, opts metav1.CreateOptions) (*v1.StateMachine, error)
	Update(ctx context.Context, stateMachine *v1.StateMachine, opts metav1.UpdateOptions) (*v1.StateMachine, error)
	UpdateStatus(ctx context.Context, stateMachine *v1.StateMachine, opts metav1.UpdateOptions) (*v1.StateMachine, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.StateMachine, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.StateMachineList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StateMachine, err error)
	StateMachineExpansion
}

// stateMachines implements StateMachineInterface
type stateMachines struct {
	client rest.Interface
	ns     string
}

// newStateMachines returns a StateMachines
func newStateMachines(c *FlowV1Client, namespace string) *stateMachines {
	return &stateMachines{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the stateMachine, and returns the corresponding stateMachine object, and an error if there is any.
func (c *stateMachines) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.StateMachine, err error) {
	result = &v1.StateMachine{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("statemachines").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StateMachines that match those selectors.
func (c *stateMachines) List(ctx context.Context, opts metav1.ListOptions) (result *v1.StateMachineList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.StateMachineList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("statemachines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested stateMachines.
func (c *stateMachines) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("statemachines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a stateMachine and creates it.  Returns the server's representation of the stateMachine, and an error, if there is any.
func (c *stateMachines) Create(ctx context.Context, stateMachine *v1.StateMachine, opts metav1.CreateOptions) (result *v1.StateMachine, err error) {
	result = &v1.StateMachine{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("statemachines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(stateMachine).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a stateMachine and updates it. Returns the server's representation of the stateMachine, and an error, if there is any.
func (c *stateMachines) Update(ctx context.Context, stateMachine *v1.StateMachine, opts metav1.UpdateOptions) (result *v1.StateMachine, err error) {
	result = &v1.StateMachine{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("statemachines").
		Name(stateMachine.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(stateMachine).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *stateMachines) UpdateStatus(ctx context.Context, stateMachine *v1.StateMachine, opts metav1.UpdateOptions) (result *v1.StateMachine, err error) {
	result = &v1.StateMachine{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("statemachines").
		Name(stateMachine.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(stateMachine).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the stateMachine and deletes it. Returns an error if one occurs.
func (c *stateMachines) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("statemachines").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *stateMachines) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("statemachines").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched stateMachine.
func (c *stateMachines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StateMachine, err error) {
	result = &v1.StateMachine{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("statemachines").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
